version: '2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.1
    container_name: kibana 
    restart: always
    network_mode: "bridge"
    ports:
      - "5601:5601"
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      - SERVER_NAME=kibana.gd
